# Generated by Django 3.1.6 on 2021-02-19 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('create_time', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(db_index=True, default=0)),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='nested_sets.node')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant', to='nested_sets.node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='noderelation',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='unique_relation'),
        ),
    ]
