# Generated by Django 3.1 on 2020-08-23 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sons', to='adjacency_list.node')),
            ],
        ),
    ]
